apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce-prod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce-prod
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-registry:8761/eureka/"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
